<?php 
    $p_id = $_GET["p_id"];
    $name = $_GET["p_name"];
    $p_name = urldecode($name);
    $fee_paid = $_GET["fee_paid"];
    $registered_by = $_GET["regBy"];
    $event_name = $_GET["event"];
    $other_members = $_GET["other"];

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="../../css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Russo+One&display=swap" rel="stylesheet">
</head>

<body>

    <center style="font-size: 20px">

        <div class="jumbotron container" style="border: 3px solid; width:300px; margin-top: 10px">
            <img width="60px" src="../../img/nuces-acm-st-chap.png" style="float:left">
            <img width="60px" src="../../img/FAST.png" style="float:right">
            <br>
            <br>
            <br>
            <br>

            <div style="text-align:center"><img width="150px" src="../../img/doomslogo.png"></div>
            
            <h1 class="display-6" style="font-family: 'Russo One', sans-serif">DOOMSDAY 19</h1>
            <p class="lead">Thank You for participating</p>

            <hr class="my-4">

            <div class="container" style="text-align:center">
                <div class="row">
                    <div class="col-md-12" style="text-align:center">Ticket ID: <?php echo $p_id ?> </div>
                </div>
                <div class="row">
                    <div class="col-md-12" style="text-align:center"> Name: <?php echo $p_name ?> </div>
                </div>
                <div class="row" style="text-align:center">
                    <div class="col-md-12">Event: <?php echo $event_name; ?> </div>
                </div>
                <div class="row" style="text-align:center">
                    <div class="col-md-12">Fee: <?php echo $fee_paid; ?> </div>
                </div>
                <?php 
                    if(!empty($other_members))
                    {
                        echo " <div class='row' style='text-align:center> ";
                        echo "     <div class='col-md-12'>Team Members: $other_members </div> ";
                        echo " </div> ";
                    }
                ?>
                <br>
                <img width="120px" src="<?php echo "./qr-generator/qrcodes/qr-".$p_id.".png"?>" style="display:block; margin-left:20px; padding-top:50px;">
                <br>
                <p style="text-align:center; font-size: 15px"> Generated By: <span style="text-decoration:underline"><?php echo $registered_by ?></span> </p>


    </center>
</body>

</html>